var tweetsData =
{
  "tweets": [
  {
    "id": "tweet1",
    "retweet_count": 1234,
    "favorite_count": 123,
    "emotion": "positive",
    "text": "Awesome tweet!",
    "hashtags": ["awesome", "super", "elte"],
  },
  {
    "id": "tweet2",
    "retweet_count": 2,
    "favorite_count": 1,
    "emotion": "neutral",
    "text": "This tweet is allright...",
    "hashtags": ["school", "elte"],
  },
  {
    "id": "tweet3",
    "retweet_count": 2125,
    "favorite_count": 24,
    "emotion": "negative",
    "text": "This tweet is totally allright...",
    "hashtags": ["NoSchool", "elte"],
  },
  {
    "id": "tweet4",
    "retweet_count": 4,
    "favorite_count": 1,
    "emotion": "neutral",
    "text": "Having fun doing Interactive media project!",
    "hashtags": ["elte"],
  },
  {
    "id": "tweet5",
    "retweet_count": 21,
    "favorite_count": 0,
    "emotion": "neutral",
    "text": "This is a tweet.",
    "hashtags": [],
  },
  {
    "id": "tweet6",
    "retweet_count": 102,
    "favorite_count": 2,
    "emotion": "negative",
    "text": "You suck!",
    "hashtags": ["YouSuck"],
  },
  {
    "id": "tweet7",
    "retweet_count": 123,
    "favorite_count": 12,
    "emotion": "neutral",
    "text": "This tweet is allright too...",
    "hashtags": ["fool"],
  },
  {
    "id": "tweet8",
    "retweet_count": 34,
    "favorite_count": 13,
    "emotion": "positive",
    "text": "Elte == tweet!",
    "hashtags": ["awesome", "elte"],
  },
  {
    "id": "tweet9",
    "retweet_count": 20,
    "favorite_count": 3,
    "emotion": "negative",
    "text": "Too many exams.",
    "hashtags": ["school"],
  }],
  "most_popular_tweets": ["tweet1", "tweet3"]
}
